### ISSUE TITLE
Document data provider rescue_image

### ISSUE THREAD

**Issue by meyskens** [src-d/terraform-provider-online#27]
We should document the usage of `data "online_rescue_image"`.
All fields are described in https://github.com/src-d/terraform-provider-online-net/blob/master/provider/data_rescue_image.go#L13 

It may be also handy to refer to `terraform-provisioner-online-rescue` which it's usage is described here: https://github.com/src-d/terraform-provisioner-online-rescue/pull/1/commits/e503145972532eddfcd9f365211ab013c18f0f77#diff-04c6e90faac2675aa89e2176d2eec7d8R39

**Comment by erindatkinson** [comment]
I can work on this.

**Comment by meyskens** [comment]
Added in #43
