### ISSUE TITLE
Prepare for Terraform 0.12

### ISSUE THREAD

**Issue by meyskens** [src-d/terraform-provider-online#52]
We should prepare this for Terraform 0.12.
This consists of
* Migrating to Go modules
* Vendoring in TF 0.12 and run tests

**Comment by meyskens** [comment]
PR: https://github.com/src-d/terraform-provider-online/pull/53

**Comment by rporres** [comment]
#53 - Reviewed. A small change and a question :)

**Comment by driosalido** [comment]
Not ready yet to review this thing ...
